name: travel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar_v2: ^6.3.2
  provider: ^6.1.5+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather_Regular.ttf
        - asset: assets/fonts/Merriweather_Bold.ttf
          weight: 700

    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSans3_Regular.ttf
        - asset: assets/fonts/SourceSans3_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSans3_Bold.ttf
          weight: 700
